# Generated by Django 2.1 on 2018-09-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=100)),
                ('agno_fundacion', models.CharField(max_length=100)),
                ('historia', models.TextField(max_length=500)),
            ],
        ),
    ]
